# Generated by Django 6.0.6 on 2026-06-17 06:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track', models.CharField(choices=[('Local', 'Local'), ('International', 'International')], max_length=20)),
                ('cto_approved', models.BooleanField(default=False)),
                ('hr_approved', models.BooleanField(default=False)),
                ('coo_approved', models.BooleanField(default=False)),
                ('ceo_approved', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('HQ', 'Root Node (HQ)'), ('CAT_A', 'Category A (Super-Distributor)'), ('CAT_B', 'Category B (Authorized Dealer)')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255)),
                ('pipeline_state', models.CharField(choices=[('Identified', 'Identified'), ('Proposal', 'Proposal'), ('Converted_To_Project', 'Converted To Project'), ('Dead', 'Dead')], default='Identified', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('stock_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_id', models.CharField(max_length=100)),
                ('locator_bin_status', models.CharField(choices=[('Fresh', 'Fresh'), ('Refurbished', 'Refurbished'), ('Repairable', 'Repairable'), ('Damaged', 'Damaged')], max_length=20)),
                ('quantity_on_hand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('marital_status', models.BooleanField(default=False, help_text='True=Married, False=Single')),
                ('base_gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgnode')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially_Paid', 'Partially Paid'), ('Settled', 'Settled'), ('Disputed', 'Disputed')], default='Unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orgnode')),
            ],
        ),
    ]
