# Generated by Django 6.0.6 on 2026-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('node', models.CharField(default='HQ-NEPAL', max_length=100)),
                ('global_telemetry', models.BooleanField(default=False)),
                ('ledger_override', models.BooleanField(default=False)),
                ('api_key_gen', models.BooleanField(default=False)),
                ('audit_log_purge', models.BooleanField(default=False)),
                ('hr_matrix_view', models.BooleanField(default=False)),
                ('fleet_command', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
