# Generated by Django 6.0.6 on 2026-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
