# Generated by Django 6.0.6 on 2026-06-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemuserprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcrm',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcrm',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
