# Generated by Django 6.0.6 on 2026-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leadcrm_address_leadcrm_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcrm',
            name='deal_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
