# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_leadcrm_deal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
