# Generated by Django 6.0.6 on 2026-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accountsreceivable_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
