# Generated by Django 6.0.6 on 2026-06-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_accountsreceivable_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='procurement_docs/'),
        ),
    ]
