# Generated by Django 5.0.4 on 2026-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inventoryledger_price_inventoryledger_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryledger',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
