# Generated by Django 5.0.4 on 2026-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inventoryledger_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='customer_name',
            field=models.CharField(default='WALK-IN CUSTOMER', max_length=255),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
