# Generated by Django 5.0.4 on 2026-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_accountsreceivable_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsreceivable',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit', 'Credit')], default='Cash', max_length=20),
        ),
    ]
