# Generated by Django 5.0.4 on 2026-06-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notice_alter_accountsreceivable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_accounts_receivable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_lead_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_leave',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_notice_board',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_procurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_profiles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_time_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadcrm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgnode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemuserprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
