# Generated by Django 5.0.4 on 2026-06-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_systemuserprofile_can_access_accounts_receivable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='password',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
