# Generated by Django 5.0.4 on 2026-06-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_systemuserprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcrm',
            name='product_inquiry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
