# Generated by Django 6.0.6 on 2026-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_calendarevent_is_female_holiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_days', models.IntegerField(default=8)),
                ('sick_leave_days', models.IntegerField(default=12)),
                ('annual_leave_days', models.IntegerField(default=15)),
                ('maternity_leave_days', models.IntegerField(default=98)),
                ('paternity_leave_days', models.IntegerField(default=15)),
            ],
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Annual', 'Annual Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave')], max_length=50),
        ),
    ]
