# Generated by Django 5.0.4 on 2026-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_staffdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
