# Generated by Django 5.0.4 on 2026-06-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_systemuserprofile_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcrm',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
