# Generated by Django 5.0.4 on 2026-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_leadcrm_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryledger',
            name='category',
            field=models.CharField(default='Electronics', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='uom',
            field=models.CharField(default='Pcs', max_length=50),
        ),
    ]
