# Generated by Django 5.0.4 on 2026-06-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_inventoryledger_category_inventoryledger_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_staff_payroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_system_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_task_board',
            field=models.BooleanField(default=False),
        ),
    ]
