# Generated by Django 5.0.4 on 2026-06-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_systemuserprofile_can_access_staff_payroll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedAttendanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('reason', models.TextField()),
                ('hr_approved', models.BooleanField(default=False)),
                ('operation_approved', models.BooleanField(default=False)),
                ('coo_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemuserprofile')),
            ],
        ),
    ]
