# Generated by Django 5.0.4 on 2026-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_missedattendancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missedattendancerequest',
            name='date',
        ),
        migrations.AddField(
            model_name='missedattendancerequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missedattendancerequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
