# Generated by Django 6.0.6 on 2026-06-30 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_procurementrequest_ceo_approver_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Operations', 'Operations & Office'), ('Payroll', 'Payroll & Benefits'), ('Marketing', 'Marketing & Sales'), ('Procurement', 'Hardware Procurement (COGS)'), ('Utilities', 'Utilities & Internet'), ('Software', 'Software & IT Subscriptions'), ('Travel', 'Travel & Transport'), ('Misc', 'Miscellaneous')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.systemuserprofile')),
            ],
        ),
    ]
