# Generated by Django 6.0.6 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_expenserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuserprofile',
            name='can_access_account_expenses',
            field=models.BooleanField(default=False),
        ),
    ]
