# Generated by Django 5.0.4 on 2026-07-01 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_accountsreceivable_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('sku_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('locator_type', models.CharField(choices=[('Fresh', 'FRESH'), ('Damaged', 'DAMAGE'), ('Refurbished', 'REFURBISHED'), ('Repairable', 'REPAIRABLE')], max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In_Transit', 'Execute Move Order: In-Transit'), ('Goods_Verified', 'Goods Verified'), ('Issue_Report', 'Issue Report Generated'), ('Completed', 'Completed - Stock Adjusted')], default='Draft', max_length=50)),
                ('checklist_driver_assigned', models.BooleanField(default=False)),
                ('checklist_vehicle_secured', models.BooleanField(default=False)),
                ('checklist_documents_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='core.orgnode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='core.orgnode')),
            ],
        ),
    ]
