# Generated by Django 5.0.4 on 2026-07-01 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_moveorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='ceo_approved',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='ceo_approver_uid',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='coo_approver_uid',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='cto_approver_uid',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='hr_approver_uid',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='is_terminal',
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='amended_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='product_sku',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='requested_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Procurement Start'), ('Pending_HR_COO', 'Review & Approve: HR & COO'), ('Pending_CTO', 'Review & Decide: CTO'), ('Pending_Amend', 'User Action: Amend Quantity'), ('Execution', 'Procurement Execution'), ('Pending_LCM', 'Post-Procurement: Integrate LCM'), ('Pending_GRN', 'GRN Process & Inventory Intake'), ('Completed', 'Process End'), ('Closed', 'Requisition Closed (Denied)')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='track',
            field=models.CharField(choices=[('Local', 'Local Procurement'), ('International', 'International Procurement')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('locator', models.CharField(max_length=50)),
                ('is_integrated', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialized_items', to='core.procurementrequest')),
            ],
        ),
    ]
